name = "cf-ddns"
main = "src/index.js"
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]

# KV 存储绑定
[[kv_namespaces]]
binding = "DDNS_CONFIG"
id = "4331cfb5536b49819719329c3b572fe9"

# 定时触发器 - 每5分钟执行
[triggers]
crons = ["*/5 * * * *"]

# 环境变量（通过 wrangler secret put 设置）
# npx wrangler secret put CF_API_TOKEN
